Repository WhileNotSuccess/project_Korean-Education-Center-Backend_NestJS-deployment-repo, pull requests merged in 2025-02, with the labels that each got.

#17 교직원, 상담 신청 API 구현
  api/src/consultation-request/consultation-request.controller.ts
  api/src/consultation-request/consultation-request.service.ts
  api/src/consultation-request/dto/create-consultation-request.dto.ts
  api/src/consultation-request/dto/update-consultation-request.dto.ts
  api/src/consultation-request/entities/consultation-request.entity.ts
  api/src/staff/dto/create-staff.dto.ts
  api/src/staff/entities/staff.entity.ts
  api/src/staff/staff.controller.ts
  api/src/staff/staff.service.ts
  api/src/users/entities/user.entity.ts
Labels: ⭐ Feature

#20 상담 신청 테이블에 name 열 추가, 정렬 추가
  api/src/consultation-request/consultation-request.controller.ts
  api/src/consultation-request/consultation-request.service.ts
  api/src/consultation-request/dto/create-consultation-request.dto.ts
  api/src/consultation-request/dto/update-consultation-request.dto.ts
  api/src/consultation-request/entities/consultation-request.entity.ts
Labels: 🐛 BugFix, ⭐ Feature

#24 테이블 분리 및 검색 기능 추가
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/attachments/attachments.controller.ts
  api/src/attachments/attachments.service.ts
  api/src/attachments/entities/post-images.entity.ts
  api/src/common/multer-fileDiskOptions.ts
  api/src/posts/posts.controller.ts
  api/src/posts/posts.service.ts
Labels: 🐛 BugFix, 🛠️ Refactor, ⭐ Feature

#30 🔨 refactor : post update 로직 변경경
  api/src/application-attachments/application-attachments.controller.ts
  api/src/application-attachments/application-attachments.service.ts
  api/src/application-form/application-form.controller.ts
  api/src/application-form/application-form.service.ts
  api/src/application-form/dto/create-application-form.dto.ts
  api/src/application-form/dto/update-application-form.dto.ts
  api/src/attachments/attachments.controller.ts
  api/src/attachments/attachments.service.ts
  api/src/banners/banners.controller.ts
  api/src/banners/banners.service.ts
  api/src/common/fileArrayFind.ts
  api/src/common/multer-fileDiskOptions.ts
  api/src/posts/dto/create-post.dto.ts
  api/src/posts/dto/update-post.dto.ts
  api/src/posts/posts.controller.ts
  api/src/posts/posts.service.ts
Labels: 🛠️ Refactor

#38 🔨 refactor : cron 작업 위치 이동, postImage 생성으로 인한 로직 변경경
  api/src/app.module.ts
  api/src/application-attachments/application-attachments.controller.ts
  api/src/application-attachments/application-attachments.service.ts
  api/src/application-form/application-form.controller.ts
  api/src/application-form/application-form.service.ts
  api/src/application-form/entities/application-form.entity.ts
  api/src/attachments/attachments.controller.ts
  api/src/attachments/attachments.service.ts
  api/src/batch/batch.controller.ts
  api/src/batch/batch.module.ts
  api/src/batch/batch.service.ts
  api/src/common/fileArrayFind.ts
  api/src/posts/posts.controller.ts
  api/src/posts/posts.service.ts
Labels: 🐛 BugFix, 🛠️ Refactor

#41 [FIX] application-form 관련 문제 수정
  api/src/application-form/application-form.controller.ts
  api/src/application-form/application-form.service.ts
  api/src/application-form/dto/update-application-form.dto.ts
Labels: 🐛 BugFix, ⭐ Feature

#47 DB 매핑, post 테이블 수정
  api/project-name@0.0.1
  api/src/app.module.ts
  api/src/application-attachments/application-attachments.controller.ts
  api/src/application-attachments/application-attachments.service.ts
  api/src/application-form/application-form.controller.ts
  api/src/application-form/application-form.service.ts
  api/src/application-form/entities/application-form.entity.ts
  api/src/attachments/attachments.controller.ts
  api/src/attachments/attachments.service.ts
  api/src/attachments/entities/post-images.entity.ts
  api/src/auth/auth.module.ts
  api/src/auth/guards/admin.guard.ts
  api/src/auth/strategies/admin.strategy.ts
  api/src/banners/banners.controller.ts
  api/src/common/fileRequired.pipe.ts
  api/src/common/utils/checkOwnership.ts
  api/src/consultation-request/consultation-request.controller.ts
  api/src/course/course.controller.spec.ts
  api/src/course/course.controller.ts
  api/src/course/course.module.ts
  api/src/course/course.service.spec.ts
  api/src/course/course.service.ts
  api/src/course/dto/create-course.dto.ts
  api/src/course/dto/update-course.dto.ts
  api/src/course/entities/course.entity.ts
  api/src/migrations/1740458631076-CreateTables.ts
  api/src/posts/dto/update-post.dto.ts
  api/src/posts/entities/post.entity.ts
  api/src/posts/posts.controller.ts
  api/src/posts/posts.service.ts
  api/src/staff/staff.controller.ts
  api/src/users/entities/user.entity.ts
  api/typeorm-ts-node-commonjs
Labels: 🐛 BugFix, ⭐ Feature

#50 🐛 fix : 동작 오류 API 수정
  api/src/application-form/application-form.service.ts
  api/src/banners/banners.controller.ts
  api/src/common/utils/checkOwnership.ts
  api/src/migrations/1740458631076-CreateTables.ts
  api/src/migrations/1740471798783-CreateTables.ts
  api/src/migrations/1740482869912-CreateTables.ts
  api/src/ormconfig.ts
  api/src/posts/dto/update-post.dto.ts
  api/src/posts/posts.controller.ts
  api/src/posts/posts.service.ts
Labels: 🐛 BugFix

#52 🐛 fix : 입학신청 페이지네이션 요청 API 수정
  api/src/application-form/application-form.controller.ts
  api/src/application-form/application-form.service.ts
  api/src/application-form/dto/create-application-form.dto.ts
  api/src/application-form/entities/application-form.entity.ts
  api/src/common/language.enum.ts
  api/src/migrations/1740552392470-CreateTables.ts
Labels: 🐛 BugFix, 🛠️ Refactor, 💻 API

#53 🐛 fix : 파일 삭제 관련 로직 변경경
  api/src/app.module.ts
  api/src/application-attachments/application-attachments.service.ts
  api/src/application-form/application-form.controller.ts
  api/src/application-form/application-form.service.ts
  api/src/application-form/dto/update-application-form.dto.ts
  api/src/attachments/attachments.service.ts
  api/src/attachments/entities/attachment.entity.ts
  api/src/attachments/entities/post-images.entity.ts
  api/src/auth/auth.controller.ts
  api/src/auth/auth.service.ts
  api/src/auth/guards/admin.guard.ts
  api/src/auth/guards/auth.guard.ts
  api/src/auth/guards/jwt-link.guard.ts
  api/src/auth/strategies/google-link.strategy.ts
  api/src/auth/strategies/google.strategy.ts
  api/src/banners/banners.controller.ts
  api/src/banners/banners.service.ts
  api/src/common/multer-fileDiskOptions.ts
  api/src/common/multer-imageDiskoptions.ts
  api/src/posts/dto/create-post.dto.ts
  api/src/posts/dto/update-post.dto.ts
  api/src/posts/posts.controller.ts
  api/src/posts/posts.service.ts
  api/src/users/dto/update-user.dto.ts
  api/src/users/users.controller.ts
Labels: 🐛 BugFix

#56 Fix/fourth fix
  api/src/application-form/application-form.controller.ts
  api/src/application-form/application-form.service.ts
  api/src/application-form/dto/create-application-form.dto.ts
  api/src/application-form/entities/application-form.entity.ts
  api/src/banners/banners.controller.ts
  api/src/banners/banners.service.ts
  api/src/course/dto/create-course.dto.ts
  api/src/course/entities/course.entity.ts
  api/src/migrations/1740641389399-CreateTables.ts
  api/src/posts/dto/create-post.dto.ts
  api/src/posts/entities/post.entity.ts
  api/src/posts/posts.controller.ts
  api/src/posts/posts.service.ts
Labels: 🐛 BugFix, ⭐ Feature, 💻 API

#58 🐛 fix : 검색기능에 언어 구분 추가
  api/src/application-form/application-form.service.ts
  api/src/posts/posts.controller.ts
  api/src/posts/posts.service.ts
Labels: 🐛 BugFix, 💻 API
